### ISSUE TITLE
WebDav File Path Question

### ISSUE THREAD

**Issue by skela** [amosavian/FileProvider#27]
So I've started playing with the WebDav file provider, to see how that fares, and I ran into a bit of an issue or question really.

Say I make a call to list the contents of a directory with a path:
"/data/Hello/Settings/background"

Everything works, and looks OK, at first glance. Except if I look at the relative path of the FileObjects I got back, its got paths like:
"/remote.php/dav/files/skela/remote.php/dav/files/skela/data/Hello/Settings/background/portrait_phones.pdf"

That to me seems wrong, for instance in Dropbox, all the paths are relative and would be for example:
"/data/Hello/Settings/background/portrait_phones.pdf"

Is this a design choice, or a possible issue ? Just asking because it feels wrong to me.

Again, really appreciate the work you do on this library!

**Comment by amosavian** [comment]
I think the problem is heading slash. I'll fix it asap

**Comment by amosavian** [comment]
@skela I found the problem, indeed server is returning an absolute path instead of relative one.
I fixed it and soon be released.

**Comment by skela** [comment]
I'm still seeing this issue even after your update. Do you think you might need to alter something in the mapToFileObject function in WebDAVFileProvider?

**Comment by amosavian** [comment]
I checked with my demo app and it works for webdav
A new issue is in Local and I'm fixing it now

**Comment by skela** [comment]
Ok so this is how I check that its not working.
I make sure I have a folder called /data/Hello/Settings , then I make sure this folder has stuff inside it, be it files or folders, it doesn't matter so much.

Then I list the contents of a the folder given the path "/data/Hello/Settings".
Take a look at the file objects you get back, (best place is to stick a break point on line 116 in the WebDAVFileProvider).

In my example, the first file's path is:
"/remote.php/dav/files/skela/remote.php/dav/files/skela/data/Hello/Settings" <-- Not only is this wrong, its including itself in the results.

If I look at the second file's path:
"/remote.php/dav/files/skela/remote.php/dav/files/skela/data/Hello/Settings/.DS_Store"

In both cases these paths are not relative, and in the first case its containing itself in the results.
The correct response in my example would be, that the first file path isn't present in the response because its path should be "/data/Hello/Settings" , which is the same as my input path exactly.

And the other file path should be:
"/data/Hello/Settings/.DS_Store"

![screen shot 2017-02-01 at 15 16 31](https://cloud.githubusercontent.com/assets/58268/22498323/9abbf032-e892-11e6-9338-4e285de76f74.png)
![screen shot 2017-02-01 at 15 18 49](https://cloud.githubusercontent.com/assets/58268/22498324/9b1cd4ba-e892-11e6-9002-16766238bb70.png)

**Comment by amosavian** [comment]
to get relative path you should use `provider.relativePathOf(url:)` or `fileObject.url.relativePath`.
The first method will resolve absolute urls too and is more safe I suppose.

I will do a new commit next hour which may provide better compatibility with different scenarios.

**Comment by skela** [comment]
FileObject.path should be the relative path of the object. At least that's according to your own comments,  and I actually think it makes a lot of sense to try and keep that consistent. This is also how it works with the Dropbox provider file objects.

**Comment by amosavian** [comment]
@skela you are right and that should be default behavior. but the WebDAV `href` returned value is tricky. Every server has a different default behavior.

e.g. `WebDAVNavServer` which I usually test against returns relative path to root, While [ajaxbrowser.com](https://www.ajaxbrowser.com) returns complete URL. The base url in the site is `https://www.ajaxbrowser.com/Userabcdefg/'`while the real base url is `https://www.ajaxbrowser.com:443/Userabcdefg/`. This little difference (ports) causes paths to not be relative anymore in parsing system.

Please find version 0.11.3, I tried to resolve `href` against `baseURL` as much as possible, but if you think there is better way to handle, you can create a pull request anytime.

**Comment by skela** [comment]
Ok understood, things can get tricky like that sometimes.
I retried with your latest code, and its still not working for my scenario.

Maybe this will help, in your latest code base for my scenario the 
node[hreftag].value is "/remote.php/dav/files/skela/data/Hello/Settings/background/"

My base url is:
"http://192.168.1.59/remote.php/dav/files/skela/"

If you supply me with the reciprocal information for your 2 scenarios, I can see I can come up with an abstraction that results in the correct answer for all 3 scenarios. 

Regardless I'll have a play with it tomorrow, and supply a pull request if successful.

**Comment by skela** [comment]
And just so I don't forget what I was talking about tomorrow, I'm referring to code inside the DavResponse initializer.

**Comment by amosavian** [comment]
Ah thanks, I got it
